iq_contentbird_api.settings:
  type: config_object
  label: 'IQ Contentbird API settings'
  mapping:
    api_token:
      type: string
      label: 'Contentbird API Token'
    api_base_url:
      type: string
      label: 'API Base URL'
    webhook_secret:
      type: string
      label: 'Webhook Secret'